import type { LessonSchemaV1 } from '../../types/lesson-schema';

export const binaryRuntimeLesson: LessonSchemaV1 = {
  schemaVersion: '1.0',
  lessonId: 'binary-runtime-demo',
  title: '万物皆数：二进制互动沙盘（Runtime）',
  subtitle: '由 JSON 课件驱动，不依赖手写页面逻辑',
  canvas: {
    width: 1100,
    height: 560,
  },
  variables: [
    { id: 'bit7', type: 'boolean', initial: false },
    { id: 'bit6', type: 'boolean', initial: false },
    { id: 'bit5', type: 'boolean', initial: false },
    { id: 'bit4', type: 'boolean', initial: false },
    { id: 'bit3', type: 'boolean', initial: false },
    { id: 'bit2', type: 'boolean', initial: false },
    { id: 'bit1', type: 'boolean', initial: false },
    { id: 'bit0', type: 'boolean', initial: false },
  ],
  nodes: [
    {
      id: 'title',
      type: 'text',
      x: 32,
      y: 24,
      props: {
        content: '点击下方灯泡切换 bit，实时观察十进制结果',
        size: 22,
        weight: 700,
        color: '#e2e8f0',
      },
    },
    {
      id: 'decimal-panel',
      type: 'panel',
      x: 32,
      y: 90,
      width: 420,
      height: 170,
      props: {
        label: '当前十进制值',
        background: 'rgba(15, 23, 42, 0.7)',
        borderColor: 'rgba(59, 130, 246, 0.35)',
      },
    },
    {
      id: 'decimal-value',
      type: 'computed-number',
      x: 48,
      y: 140,
      width: 388,
      height: 100,
      props: {
        label: 'DECIMAL',
        formula: 'binary_sum',
        sources: [
          { variableId: 'bit7', weight: 128 },
          { variableId: 'bit6', weight: 64 },
          { variableId: 'bit5', weight: 32 },
          { variableId: 'bit4', weight: 16 },
          { variableId: 'bit3', weight: 8 },
          { variableId: 'bit2', weight: 4 },
          { variableId: 'bit1', weight: 2 },
          { variableId: 'bit0', weight: 1 },
        ],
      },
    },
    {
      id: 'bits-panel',
      type: 'panel',
      x: 32,
      y: 290,
      width: 1036,
      height: 220,
      props: {
        label: '二进制位开关（MSB -> LSB）',
        background: 'rgba(2, 6, 23, 0.7)',
        borderColor: 'rgba(148, 163, 184, 0.35)',
      },
    },
    { id: 'bit7-node', type: 'toggle', x: 70, y: 350, width: 95, height: 120, props: { variableId: 'bit7', label: '128' } },
    { id: 'bit6-node', type: 'toggle', x: 188, y: 350, width: 95, height: 120, props: { variableId: 'bit6', label: '64' } },
    { id: 'bit5-node', type: 'toggle', x: 306, y: 350, width: 95, height: 120, props: { variableId: 'bit5', label: '32' } },
    { id: 'bit4-node', type: 'toggle', x: 424, y: 350, width: 95, height: 120, props: { variableId: 'bit4', label: '16' } },
    { id: 'bit3-node', type: 'toggle', x: 542, y: 350, width: 95, height: 120, props: { variableId: 'bit3', label: '8' } },
    { id: 'bit2-node', type: 'toggle', x: 660, y: 350, width: 95, height: 120, props: { variableId: 'bit2', label: '4' } },
    { id: 'bit1-node', type: 'toggle', x: 778, y: 350, width: 95, height: 120, props: { variableId: 'bit1', label: '2' } },
    { id: 'bit0-node', type: 'toggle', x: 896, y: 350, width: 95, height: 120, props: { variableId: 'bit0', label: '1' } },
  ],
  timeline: [
    {
      id: 'intro',
      atMs: 0,
      title: '第 1 步：观察结果区',
      description: '十进制结果由下方所有 bit 共同决定。',
      focusNodeId: 'decimal-value',
    },
    {
      id: 'high-bits',
      atMs: 2000,
      title: '第 2 步：高位权重更大',
      description: '左侧高位 bit（128/64）切换一次，影响最明显。',
      focusNodeId: 'bit7-node',
    },
    {
      id: 'low-bits',
      atMs: 4000,
      title: '第 3 步：低位用于微调',
      description: '右侧低位 bit（2/1）用于精确调节数值。',
      focusNodeId: 'bit1-node',
    },
    {
      id: 'challenge',
      atMs: 6000,
      title: '第 4 步：自由组合',
      description: '试着拼出 255、170、42，验证你对二进制的掌握。',
      focusNodeId: 'bits-panel',
    },
  ],
};
